version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_scut-infohub-back-end
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=scut-infohub-back-end
      - role=container
    environment:
      - MYSQL_USERNAME=
      - MYSQL_PASSWORD=
      - MYSQL_ADDRESS=
      - MYSQL_ADDRESS=host.docker.internal:3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=z250010
      - WeChat_Appid=wx63e3c1951a272c10
      - WeChat_Appsecret=9dda7f80ad3bf406a73016575784c001
networks:
  default:
    external:
      name: wxcb0
